run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: var-naming

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - errcheck
    - path: main\.go
      linters:
        - unparam
  max-same-issues: 10
  max-issues-per-linter: 10
